<!-- quote-generator-form.php -->
<?php
global $wpdb;
$current_year = date("Y");
$current_user = null;

if (is_user_logged_in()) {
    $current_user = wp_get_current_user();
}

$history = $wpdb->get_results("SELECT * FROM wp_quote_history WHERE user_id = $current_user->ID ORDER BY quotation_date DESC");

?>
<div class="header-container">
    <h1>TBS Price Quotation Generator <sub><?php echo $current_year; ?></sub></h1>
    <button value="Generate Quote" id="openHistory" class="btn btn-primary">History</button>
</div>

<div id="history_popup" class="popup">
    <div class="popup-content">
        <span class="close">&times;</span>
        <div class="popup-header">
            <h1>Quote History</h1>
            <p>Quote generated by <strong><?php echo $current_user->display_name; ?></strong></p>
        </div>
        <?php
        foreach ($history as $quote) {
            $details = json_decode($quote->details);
            $items = $details->items;
            $running_number = $quote->revision_number == '0' ? $quote->running_number : $quote->running_number . "_R" . $quote->revision_number;

            echo "<div class='quote-item'>";
            echo "<div class='quote-header' onclick='toggleDetails(this)'>";
            echo "<h3 class='quote-title'>$running_number - $details->client_name - $details->total_amount $details->currency</h3>";
            $safe = esc_attr( json_encode($details) );
            echo "<button type='button' class='quote-button import-quote-btn' data-details='{$safe}'>Import</button>";
            echo "</div>";
            echo "<div class='quote-details' style='display: none;'>";
            
            // รวบรวมชื่อ service ที่ไม่ซ้ำกัน
            $unique_services = array();
            if (!empty($items)) {
                foreach ($items as $service) {
                    $svc_name = isset($service->service_name) ? trim($service->service_name) : '';
                    if (!empty($svc_name) && !in_array($svc_name, $unique_services)) {
                        $unique_services[] = $svc_name;
                    }
                }
            }
            
            // แสดงส่วน Services Used
            if (!empty($unique_services)) {
                echo "<div class='services-used' style='margin-bottom: 15px; padding: 10px 15px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); border-radius: 8px; color: white; box-shadow: 0 2px 4px rgba(0,0,0,0.1);'>";
                echo "<strong style='font-weight: 600;'>Services Used:</strong> ";
                echo esc_html(implode(', ', $unique_services));
                echo "</div>";
            }
            
            echo "<div class='details-grid'>";
            echo "<div class='details-column'>";
            echo "<ul>";
            echo "<li>Quotation Valid Date: $details->quotation_valid_date</li>";
            echo "<li>Client Name: $details->client_name</li>";
            echo "<li>Client Address: $details->client_address</li>";
            echo "<li>Client Email: $details->client_email</li>";
            echo "<li>Client Phone: $details->client_phone</li>";
            echo "<li>Project Description: $details->project_desc</li>";
            echo "<li>Company Name: $details->company_name</li>";
            echo "<li>Full Name: $details->full_name</li>";
            echo "<li>Company Address: $details->company_address</li>";
            echo "<li>Company Email: $details->company_email</li>";
            echo "<li>Company Phone: $details->company_phone</li>";
            echo "</ul>";
            echo "</div>";
            echo "<div class='details-column'>";
            echo "<ul>";
            echo "<li>Customer Tax ID: $details->customer_tax_id</li>";
            echo "<li>Remark: $details->remark</li>";
            echo "<li>Discount Type: $details->discount_type</li>";
            echo "<li>Discount: $details->discount</li>";
            echo "<li>VAT Percentage: $details->vat_percentage</li>";
            echo "<li>Currency: $details->currency</li>";
            echo "<li>Total Amount: $details->total_amount</li>";
            echo "<li>Discount Sub Total: $details->discount_sub_total</li>";
            echo "<li>VAT Amount: $details->vat_amount</li>";
            echo "<li>Total Amount with VAT: $details->total_amount_with_vat</li>";
            echo "</ul>";
            echo "</div>";
            echo "</div>";
            
            // จัดกลุ่ม items ตาม group_id
            $grouped_items = array();
            if (!empty($items)) {
                foreach ($items as $service) {
                    $group_id = isset($service->group_id) ? $service->group_id : 'ungrouped';
                    if (!isset($grouped_items[$group_id])) {
                        $grouped_items[$group_id] = array();
                    }
                    $grouped_items[$group_id][] = $service;
                }
            }
            
            // ดึง service_group_name จาก details
            $service_group_names = isset($details->service_group_name) ? (array)$details->service_group_name : array();
            
            // แสดงตารางแยกตาม service group
            if (!empty($grouped_items)) {
                foreach ($grouped_items as $group_id => $group_services) {
                    // ลองหาชื่อจาก service_group_name ก่อน
                    $service_name = '';
                    if (isset($service_group_names[$group_id]) && !empty($service_group_names[$group_id])) {
                        $service_name = $service_group_names[$group_id];
                    } else {
                        // ถ้าไม่มีใน service_group_name ให้หาจาก service_name ของ items
                        foreach ($group_services as $svc) {
                            if (!empty($svc->service_name)) {
                                $service_name = $svc->service_name;
                                break;
                            }
                        }
                    }
                    
                    if (empty($service_name)) {
                        $service_name = 'General Services';
                    }
                    
                    // คำนวณ total ของกลุ่ม
                    $group_total = 0;
                    foreach ($group_services as $svc) {
                        $group_total += isset($svc->total_price) ? (float)$svc->total_price : 0;
                    }
                    
                    echo "<div style='margin-bottom: 25px;'>";
                    echo "<h4 style='background: #3C3D3A; color: white; padding: 10px; margin: 0; border-radius: 5px 5px 0 0;'>Service: " . esc_html($service_name) . "</h4>";
                    echo "<table class='table table-striped' style='margin-bottom: 0; border: 1px solid #dee2e6;'>";
                    echo "<thead style='background-color: #f8f9fa;'><tr><th>#</th><th>Description</th><th>Qty</th><th>Unit Price</th><th>Total</th></tr></thead>";
                    echo "<tbody>";
                    
                    $row_counter = 1;
                    foreach ($group_services as $service) {
                        $row_id = isset($service->row_id) ? $service->row_id : '';
                        $is_parent = (strpos($row_id, '.') === false);
                        $display_id = $is_parent ? $row_counter++ : $row_id;
                        
                        $desc = isset($service->description) ? esc_html($service->description) : '';
                        $qty = isset($service->quantity) ? esc_html($service->quantity) : '0';
                        $price = isset($service->price) ? number_format((float)$service->price, 2) : '0.00';
                        $total = isset($service->total_price) ? number_format((float)$service->total_price, 2) : '0.00';

                        $font_weight = $is_parent ? 'font-weight: bold;' : '';
                        
                        echo "<tr>";
                        echo "<td style='$font_weight'>{$display_id}</td>";
                        echo "<td>{$desc}</td>";
                        echo "<td>{$qty}</td>";
                        echo "<td>{$price}</td>";
                        echo "<td>{$total}</td>";
                        echo "</tr>";
                    }
                    
                    echo "</tbody>";
                    echo "</table>";
                    echo "</div>";
                }
            } else {
                echo "<p style='text-align: center; padding: 20px; color: #6c757d;'>No services found in this quote.</p>";
            }
            
            echo "</div>";
            echo "</div>";
        }
        ?>
    </div>
</div>


<form id="price_quotation_form" method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"
    target="_blank" class="container mt-4">
    <input type="hidden" name="action" value="process_quote_form">

    <!-- Currency Selection -->
    <div class="form-group">
        <label for="currencySwitch" class="form-label">Select Currency:</label>
        <div class="form-check form-switch form-check-inline">
            <input class="form-check-input" type="radio" id="thbCurrency" name="currency" value="THB" checked>
            <label class="form-check-label" for="thbCurrency">THB</label>
        </div>
        <div class="form-check form-switch form-check-inline">
            <input class="form-check-input" type="radio" id="usdCurrency" name="currency" value="USD">
            <label class="form-check-label" for="usdCurrency">USD</label>
        </div>
        <div class="form-check form-switch form-check-inline">
            <input class="form-check-input" type="radio" id="gbpCurrency" name="currency" value="GBP">
            <label class="form-check-label" for="gbpCurrency">GBP</label>
        </div>
        <div class="form-check form-switch form-check-inline">
            <input class="form-check-input" type="radio" id="sgdCurrency" name="currency" value="SGD">
            <label class="form-check-label" for="sgdCurrency">SGD</label>
        </div>
        <div class="form-check form-switch form-check-inline">
            <input class="form-check-input" type="radio" id="eurCurrency" name="currency" value="EUR">
            <label class="form-check-label" for="eurCurrency">EUR</label>
        </div>
    </div>


    <!-- Logo section -->
    <h3>General Information</h3>
    <div class="row">
        <div class="col-md-6">
            <!-- Quotation Date -->
            <div class="form-group">
                <label for="quotation_date">Date Created:</label>
                <input type="date" id="quotation_date" name="quotation_date" class="form-control">
            </div>
        </div>
        <div class="col-md-6">
            <!-- Quotation Valid Until Date -->
            <div class="form-group">
                <label for="quotation_valid_date">Valid Until Date:</label>
                <input type="date" id="quotation_valid_date" name="quotation_valid_date" class="form-control">
            </div>
        </div>
    </div>

    <!-- Project Description -->
    <div class="form-group">
        <label for="project_desc" class="sr-only">Quote/Project Description:</label>
        <textarea name="project_desc" id="project_desc" class="form-control" rows="5"
            placeholder="Enter Quote/Project Description"></textarea>
        <span style="font-size: 14px;">‣ Copy Paste ( • ○ ) for bullet points.</span>
    </div>

    <!-- Team Member  -->
    <div class="row">
        <div class="col-md-6">
            <label for="revised_quotation" class="form-label">Is this a revised quotation?</label>
            <select name="revised_quotation" id="revised_quotation" class="form-select">
                <option value="false" selected>No</option>
                <option value="true">Yes</option>
            </select>
            <input type="hidden" name="running_number" id="running_number">

        </div>
        <div class="col-md-4">
            <label for="team_dropdown" class="form-label">Select your Name to Autofill Information</label>
            <select id="team_dropdown" class="form-select" style="margin-bottom:20px;">
            </select>
        </div>
    </div>

    <!-- Company Information and Quotation To side by side -->
    <div class="row">
        <div class="col-md-6">
            <h3>Client Information</h3>
            <div class="form-group">
                <label class="sr-only" for="client_name">Client Company Name:</label>
                <input type="text" id="client_name" name="client_name" placeholder="Enter client company name" class="form-control">
            </div>
            <!-- Customer Tax ID -->
            <div class="form-group">
                <label class="sr-only" for="customer_tax_id">Valid Until Date:</label>
                <input type="text" id="customer_tax_id" name="customer_tax_id" placeholder="Customer Tax ID" class="form-control">
            </div>
            <div class="form-group">
                <label class="sr-only" for="client_address">Address:</label>
                <input type="text" id="client_address" name="client_address" placeholder="Enter client address" class="form-control">
            </div>
            <div class="form-group">
                <label class="sr-only" for="client_email">Email:</label>
                <input type="email" id="client_email" name="client_email" placeholder="Enter client email" class="form-control">
            </div>
            <div class="form-group">
                <label class="sr-only" for="client_phone">Phone:</label>
                <input type="tel" id="client_phone" name="client_phone" placeholder="Enter client phone" class="form-control">
            </div>
        </div>
        <div class="col-md-6">
            <h3>Our Information</h3>
            <div class="form-group">
                <label class="sr-only" for="company_name">Company Name:</label>
                <input type="text" id="company_name" name="company_name" value="The Business SEO Co., Ltd (Trading as TBS Marketing)"
                    placeholder="Enter company name" class="form-control">
            </div>
            <div class="form-group">
                <label class="sr-only" for="full_name">Your Full Name:</label>
                <input type="text" id="full_name" id="full_name" name="full_name" placeholder="Enter Full name" class="form-control">
            </div>
            <div class="form-group">
                <label class="sr-only" for="company_address">Address:</label>
                <input type="text" id="company_address" name="company_address"
                    value="1023, 4th Floor TPS Building Pattanakarn Road, Suanluang, Bangkok, Thailand, 10250"
                    placeholder="Enter company address" class="form-control">
            </div>
            <div class="form-group">
                <label class="sr-only" for="company_email">Email:</label>
                <input type="email" id="company_email" name="company_email" placeholder="Enter your company email"
                    class="form-control">
            </div>
            <div class="form-group">
                <label class="sr-only" for="company_phone">Phone:</label>
                <input type="tel" id="company_phone" name="company_phone" placeholder="Enter your company mobile"
                    class="form-control">
            </div>
        </div>
    </div>

    <!-- Items: Service Groups -->
    <h3>Services</h3>
        <div class="col-md-7">
            <div class="form-group"> 
                <label for="column_to_print" class="form-label">Select column to print:</label>
                <div class="form-check form-switch form-check-inline">
                    <input class="form-check-input" type="checkbox" id="service_dropdown" name="column_to_print[]" value="Qty"
                        checked>
                    <label class="form-check-label" for="qtyColumn">Qty</label>
                </div>
                <div class="form-check form-switch form-check-inline">
                    <input class="form-check-input" type="checkbox" id="rateColumn" name="column_to_print[]"
                        value="Rate" checked>
                    <label class="form-check-label" for="rateColumn">Rate</label>
                </div>
                <div class="form-check form-switch form-check-inline">
                    <input class="form-check-input" type="checkbox" id="Quotation-number" name="column_to_print[]" value="Quotation-number" checked>
                    <label class="form-check-label" for="Quotation-number">Quotation number</label>

                </div>
            </div>
        </div>
        
    <div id="service_groups_container">
        <!-- Service groups will be dynamically added here by JS. Each group contains its own dropdown, table and controls. -->
    </div>

    <div class="row" style="margin-top:10px;">
        <div class="col-md-12">
            <button type="button" id="add_service_group" class="btn btn-outline-primary">Add new Service</button>
            <p style="margin-top:8px; font-size:0.9em; color:#555;"></p>
        </div>
    </div>

    <div class="row">
        <!-- Remark -->
        <div class="col-md-6">
            <label for="remark" class="sr-only">Remark:</label>
            <textarea name="remark" id="remark" class="form-control" rows="10"
                placeholder="Enter any remarks here"></textarea>
            <span style="font-size: 14px;">‣ Copy Paste ( • ○ ) for bullet points.</span>
        </div>
        <!-- Prices -->
        <div class="col-md-6">
            <!-- Total Amount -->
            <div class="form-group">
                <p for="total_amount">Total Amount (excluding VAT) - <span id="total_amount_label"
                        class="font-weight-bold">0.00 THB</span></p>

                <input type="text" id="total_amount_input" name="total_amount_without_vat_and_discount" class="font-weight-bold d-none" value="0.00" readonly>
            </div>

            <!-- Discount Type -->
            <div class="form-group row">
                <label for="discount_type" class="col-sm-3 col-form-label">Discount Type:</label>
                <div class="col-sm-9">
                    <select name="discount_type" id="discount_type" class="form-control">
                        <option value="percentage">Percentage (%)</option>
                        <option value="fixed">Fixed Amount (THB)</option>
                    </select>
                </div>
            </div>

            <!-- Discount -->
            <div class="form-group row">
                <label for="discount" class="col-sm-3 col-form-label">Discount:</label>
                <div class="col-sm-9">
                    <input type="number" name="discount" id="discount" value="0" class="form-control" min="0"
                        step="0.01">
                </div>
            </div>

            <!-- VAT Percentage -->
            <div class="form-group row">
                <label for="vat_percentage" class="col-sm-3 col-form-label">VAT %:</label>
                <div class="col-sm-9">
                    <input type="number" name="vat_percentage" id="vat_percentage" class="form-control" value="7"
                        min="0" max="100" step="1">
                </div>
            </div>

            <!-- VAT Amount -->
            <div class="form-group">
                <p for="vat_amount">VAT Amount - <span id="vat_amount_label" class="font-weight-bold">0.00 THB</span>
                </p>
                <!-- <label for="vat_amount">VAT Amount - </label> -->
                <input type="text" id="vat_amount_input" name="total_vat_amount" class="font-weight-bold d-none" value="0.00" readonly>

            </div>

            <!-- Total Amount with VAT -->
            <div class="form-group">
                <p for="total_amount_with_vat">
                    Total Amount (including VAT) -
                    <span id="total_amount_with_vat_label" class="font-weight-bold">0.00 THB</span>

                    <input
                        type="number"
                        id="month_number_input"
                        min="1"
                        max="12"
                        value="1"
                        style="display: none; width: 60px; padding: 2px 5px; font-size: 0.9em; margin-left: 5px; vertical-align: middle;" />

                    <select id="monthly_price"
                        style="display: none; width: auto; min-width: 90px; padding: 2px 5px; margin-left: 5px; font-size: 0.9em; vertical-align: middle;">
                        <option value="Month">/ Month</option>
                        <option value="Year">/ Year</option>
                    </select>
                </p>

                <input type="text" id="total_amount_with_vat_input" name="total_amount_with_vat" class="font-weight-bold d-none" value="0.00" readonly>
                <input type="hidden" name="monthly_price_input" id="monthly_price_input" value="1 Month">
            </div>


        </div>
    </div>

    <!-- Submit Button -->
    <button type="submit" value="Generate Quote" class="btn btn-success">Generate Quote</button>
</form>
